name: ${plugin.name}
description: ${project.description}
main: ${plugin.mainClass}
version: ${project.version}
authors: [The Avicus Network, JasorYEH]
website: https://github.com/VectorMC/AvicusNetwork